# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: lovingliu
    jedis:
      pool:
        max-active: 10 #最大连接数
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 10 #最大空闲
        min-idle: 0 #最小空闲
    timeout: 10000 #链接超时时间
