package cn.lovingliu.rabbitmqproducer.domain;

import java.io.Serializable;
import java.util.Date;

public class MessageLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broker_message_log.message_id
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broker_message_log.message
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broker_message_log.try_count
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    private Integer tryCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broker_message_log.status
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broker_message_log.next_retry
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    private Date nextRetry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broker_message_log.create_time
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column broker_message_log.update_time
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table broker_message_log
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broker_message_log.message_id
     *
     * @return the value of broker_message_log.message_id
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broker_message_log.message_id
     *
     * @param messageId the value for broker_message_log.message_id
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broker_message_log.message
     *
     * @return the value of broker_message_log.message
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broker_message_log.message
     *
     * @param message the value for broker_message_log.message
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broker_message_log.try_count
     *
     * @return the value of broker_message_log.try_count
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public Integer getTryCount() {
        return tryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broker_message_log.try_count
     *
     * @param tryCount the value for broker_message_log.try_count
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public void setTryCount(Integer tryCount) {
        this.tryCount = tryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broker_message_log.status
     *
     * @return the value of broker_message_log.status
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broker_message_log.status
     *
     * @param status the value for broker_message_log.status
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broker_message_log.next_retry
     *
     * @return the value of broker_message_log.next_retry
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public Date getNextRetry() {
        return nextRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broker_message_log.next_retry
     *
     * @param nextRetry the value for broker_message_log.next_retry
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public void setNextRetry(Date nextRetry) {
        this.nextRetry = nextRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broker_message_log.create_time
     *
     * @return the value of broker_message_log.create_time
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broker_message_log.create_time
     *
     * @param createTime the value for broker_message_log.create_time
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column broker_message_log.update_time
     *
     * @return the value of broker_message_log.update_time
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column broker_message_log.update_time
     *
     * @param updateTime the value for broker_message_log.update_time
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", messageId=").append(messageId);
        sb.append(", message=").append(message);
        sb.append(", tryCount=").append(tryCount);
        sb.append(", status=").append(status);
        sb.append(", nextRetry=").append(nextRetry);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}