package cn.lovingliu.rabbitmqproducer.dao;

import cn.lovingliu.rabbitmqproducer.domain.MessageLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MessageLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    int deleteByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    int insert(MessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    int insertSelective(MessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    MessageLog selectByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    int updateByPrimaryKeySelective(MessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbg.generated Tue Sep 24 23:15:58 CST 2019
     */
    int updateByPrimaryKey(MessageLog record);

    /**
     * @Desc 设置尝试重新生产此消息的次数
     * @Author LovingLiu
    */
    int update4ReSend(String messageId);

    int changeBrokerMessageLogStatus(@Param("messageId")String messageId,@Param("status")String status);

    List<MessageLog> query4StatusAndTimeoutMessage();
}